* Vision is the most important sense used while driving
** Rain can cause loss of vision: use of wipers, slow down to 30kph
** An accident that affects your eyes: passenger can help
** Headlights not switched on or not working: don't start car without switching on headlights AND confirming they are on. Routine.
** Windshield dirty: always clean car yourself so this does not happen 
** Splash of dirty water on windshield when passing heavy vehicle: wipers in working condition
** Medical issues with eyes: regular eye checks and naturalistic checks on road
** Light outside too bright: check vision with doctor. Flaps and their proper use
**  Driving without lights is the worst situation to get in
** Keep lights always on and on low beam like they do in Scandinavian countries. Switch to high beam in evening or night
** Always check lights, seatbelt, brakes when you get into the car
 - vision is the most important sense required for driving. Vision is impaired by the following:
* Trust your vehicle that's well maintained
** Most crashes (80%) are due to human error-not due to vehicle system malfunction
* The nut behind the wheel problem
** Practical experience builds skill
**  However practicing in safe environment-with a skilled driver is necessary
** In addition a good dose of bookish knowledge using Police Manual can help. It can't replace practice
* Intimate knowledge about the vehicle switches and in what scenario each switch or lever can be used
2. Not having lights at night
3. Distractions that take your eyes off the roadway- texting, calling, talking with someone in the car, looking at billboards
4. System 1 vs system 2 thinking. System 1 makes you jump to conclusions. Hence you need to rehearse situations and have a troubleshooting map identified beforehand
5. Most of the times the systems of a well maintained car function properly. especially critical systems like brakes, lights. When in doubt first trust these systems before making any drastic decisions
* Personal rookie mistakes
- Not slowing down in case of danger. Where you need medium grade braking at 4m/s^2. This needs practice
- Forgetting what to do in case suddenly lights go out-you need to switch on headlights first. In fact before all of that just use the flasher so it will activate both beams
