* Vision is the most important sense used while driving

** What can cause loss of effective road vision?
   1. Not switching on lights
   2. Lights not functional though switched on
   3. [ *Surprise* ]
      - Sudden weather change
      - Suddenly lights on road go out (municipal lights)
      - Sudden entry into tunnel so not enough time to switch on -surprised.
      - Sudden entry into parking lot
   4. [ *Obstruction* ]
      - *Curved* road
      - *Wavy* road
      - *Tailgating* vehicle in front very closely
      - Trees
      - Sudden tarpaulin or some object flying out of lead vehicle
   5. *Glare* from oncoming vehicles
   6. Falling asleep
   7. Distracted by :
      - Phone
      - Kids
      - Passenger talking
      - *Eyes off road* for more than 1 second

** What causes reduced TTC ?
** Rain can cause loss of vision: use of wipers, slow down to 30kph
** An accident that affects your eyes: passenger can help
** Headlights not switched on or not working: don't start car without switching on headlights AND confirming they are on. Routine.
** Windshield dirty: always clean car yourself so this does not happen
** Splash of dirty water on windshield when passing heavy vehicle: wipers in working condition
** Medical issues with eyes: regular eye checks and naturalistic checks on road
** Light outside too bright: check vision with doctor. Flaps and their proper use
** Backup with a capable torch that's easily accessible? :safety:
**  Driving without lights is the worst situation to get in
** Keep lights always on and on low beam like they do in Scandinavian countries. Switch to high beam in evening or night
** Always check lights, seatbelt, brakes when you get into the car
 - vision is the most important sense required for driving. Vision is impaired by the following:
* Trust your vehicle that's well maintained
** Most crashes (80%) are due to human error-not due to vehicle system malfunction
* The nut behind the wheel problem
** Practical experience builds skill
**  However practicing in safe environment-with a skilled driver is necessary
** In addition a good dose of bookish knowledge using Police Manual can help. It can't replace practice however
* Predicting what will happen based on men model and comparing with actually what happens-less errors means more skill :mental_model:situational_awareness:
* Indications of poor situational awareness
** Fixation on a single approach/line of action with blinders and exclusion of all other solutions. Stopping the prediction loop. It's ok if it happens when focus is needed but after the critical phase is over a reappraisal is needed. :constant_appraisal_of_situation:
* Intimate knowledge about the vehicle switches and in what scenario each switch or lever can be used. You get 2-3 seconds to think and decide on a course of action. Clarity of previous experiences is essential so that you don't form wrong schemas.
2. Not having lights at night
3. Distractions that take your eyes off the roadway- texting, calling, talking with someone in the car, looking at billboards
4. System 1 vs system 2 thinking. System 1 makes you jump to conclusions. Hence you need to rehearse situations and have a troubleshooting map identified beforehand
5. Most of the times the systems of a well maintained car function properly. especially critical systems like brakes, lights. When in doubt first trust these systems before making any drastic decisions
* Personal rookie mistakes
- Not slowing down in case of danger. Where you need medium grade braking at 4m/s^2. This needs practice
- Forgetting what to do in case suddenly lights go out-you need to switch on headlights first. In fact before all of that just use the flasher so it will activate both beams
* Planning mistakes/biases
  1. *Confirmatory bias* seek out information that will confirm my theory . "Got input that lights did not work even after toggling low->high beam and back. But explained away as terrain is uneven and hence this is happening or that the lights will not work/will not work in this situation and something else needs to be tried out" This prevented me from trying out switching on the headlights using the headlights ON switch. I continued in this fallacy right till I reached home and hence did not take efforts to correct it in any way
  2. *Resistance to change* not willing to change the plan/belief and searching for alternate explanations that justify the original hypothesis/model. "Once I held the belief that the headlight system had failed then I tried auxiliary systems which also did not work. Then I gave up on the lights and focused on steering and with whatever vision I had in the time around nautical twilight and the mental model that in middle lane trucks won't stop. I had about 17m of visibility  on the road (maybe more for a large obstacle) which at my speed was like 1.7 seconds of reaction time.
  3. *Simplistic understanding of causality* only one cause for an issue and hence fixing that cause will fix issue. Or wrong causal model. "The stick is at low beam and if I move to high beam it will be ok". "The terrain is wavy and hence the lights are not taking effect"
  4. One mistake that was unpardonable was *not pressing brakes to slow down*. I think I was at 45kph down the slope and then at 30-35kph when I was near the garbage truck. I should have slowed down immediately to 25kph from 45kph since a rear underrun at 45kph can be fatal. It can especially be fatal to passenger side occupants if it's a small overlap-which the situation would have been most likely if I had not "seen" the garbage truck.
** TODO This is a case where practice alone works. Theory does not work. I need to try out braking comfortably to get confident and so that it becomes an automated response when there's any danger of front-rear collision. :fc:
   SCHEDULED: <2021-07-03 Sat>
   :PROPERTIES:
   :FC_CREATED: 2021-05-04T12:00:42Z
   :FC_TYPE:  normal
   :ID:       EC8760F6-E6F7-476E-A61D-CF91AE6A7323
   :END:
   :REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    |  2.5 |   0 |        0 | 2021-05-04T12:00:42Z |
   :END:
