*  Driving without lights is the worst situation to get in
** Keep lights always on and on low beam like they do in Scandinavian countries. Switch to high beam in evening or night
 - Always check lights, seatbelt, brakes when you get into the car
 - vision is the most important sense required for driving. Vision is imparied by the following:
 1. Not having lights at night
 2. Distractions that take your eyes off the roadway- texting, calling, talking with someone in the car, looking at billboards
 - System 1 vs system 2 thinking. System 1 makes you jump to conclusions. Hence you need to rehearse situations and have a troubleshooting map identified beforehand
 - Most of the times the systems of a well maintained car function properly. especially critical systems like brakes, lights. When in doubt first trust these systems before making any drastic decisions
* Personal rookie mistakes
- Not slowing down in case of danger. Where you need medium grade braking at 4m/s^2. This needs practice
- Forgetting what to do in case suddenly lights go out-you need to switch on headlights first. In fact before all of that just use the flasher so it will activate both beams
