* Always be situationally aware.
** If you are driving be aware of a)state of your car controls [lights on/off, indicators, mirror positions, gear position etc.] b)state of weather around you [day or night, rain, snow, bright sunlight, smoke]. Eg: trucks are parked on left lanes, shoulders rampantly at night with no hazards on. Disabled vehicles are parked in the lane in which they are disabled. Altogether this makes night driving risky. c)traffic around you [who's to  front, front of front, left, to right, behind] d)country/city in which you are driving and the official and unofficial driving patterns at that place e)awareness of the primary sources of fatal accidents in that city/state/country/road condition. Eg: front to rear underrun with LCVs is the primary source of fatality on national highways and other divided roads in India. e)road condition: National highway, state highway, curved road, uphill, downhill [visibility is reduced in these cases], one way two way, one way with possibility of stupid traffic in opposite direction
*  When driving always keep eyes on forward carriageway
  Distracted driving (eyes not on forward carriageway) is the primary controllable cause of accidents.
* Be entirely conversant with the car controls. You should be able to use the controls even in your sleep. Try not to use someone else's car if possible/use a car which you are used to
  Complete information about car controls and complete info about the state of the car controls, traffic and weather help you navigate and take right decisions.
* Driving is not intuitive or instinctive
  Hence, we need to be especially careful in the night since vision is the most important sense for driving and humans can't see in the night.
